// <auto-generated />
using System;
using AngularDemoSeeds.EntityFrameworkCore.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularDemoSeeds.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AngularDemoSeedDbContext))]
    [Migration("20230328105704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.CustomerMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pincode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CustomerMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Customer 1",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(452),
                            CustomerName = "Customer 1",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 1",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Customer 2",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(456),
                            CustomerName = "Customer 2",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 2",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Customer 3",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(459),
                            CustomerName = "Customer 3",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 3",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "Customer 4",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(461),
                            CustomerName = "Customer 4",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 4",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "Customer 5",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(463),
                            CustomerName = "Customer 5",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 5",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 5
                        },
                        new
                        {
                            Id = 6,
                            Address = "Customer 6",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(465),
                            CustomerName = "Customer 6",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 6",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 6
                        },
                        new
                        {
                            Id = 7,
                            Address = "Customer 7",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(467),
                            CustomerName = "Customer 7",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 7",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 7
                        },
                        new
                        {
                            Id = 8,
                            Address = "Customer 8",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(469),
                            CustomerName = "Customer 8",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 8",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 8
                        },
                        new
                        {
                            Id = 9,
                            Address = "Customer 9",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(471),
                            CustomerName = "Customer 9",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 9",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 9
                        },
                        new
                        {
                            Id = 10,
                            Address = "Customer 10",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(473),
                            CustomerName = "Customer 10",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 10",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 10
                        },
                        new
                        {
                            Id = 11,
                            Address = "Customer 11",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(475),
                            CustomerName = "Customer 11",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 11",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 11
                        },
                        new
                        {
                            Id = 12,
                            Address = "Customer 12",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(478),
                            CustomerName = "Customer 12",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 12",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 12
                        },
                        new
                        {
                            Id = 13,
                            Address = "Customer 13",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(480),
                            CustomerName = "Customer 13",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 13",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 13
                        },
                        new
                        {
                            Id = 14,
                            Address = "Customer 14",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(482),
                            CustomerName = "Customer 14",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 14",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 14
                        },
                        new
                        {
                            Id = 15,
                            Address = "Customer 15",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(484),
                            CustomerName = "Customer 15",
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Customer 15",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9876543210",
                            Pincode = 15
                        });
                });

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.OrderDetailMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderMasterId")
                        .HasColumnType("int");

                    b.Property<int>("ProductMasterId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderMasterId");

                    b.HasIndex("ProductMasterId");

                    b.ToTable("OrderDetailMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderMasterId = 1,
                            ProductMasterId = 1,
                            Quantity = 1,
                            TotalAmount = 12.15m
                        },
                        new
                        {
                            Id = 2,
                            OrderMasterId = 2,
                            ProductMasterId = 2,
                            Quantity = 1,
                            TotalAmount = 20m
                        },
                        new
                        {
                            Id = 3,
                            OrderMasterId = 3,
                            ProductMasterId = 3,
                            Quantity = 1,
                            TotalAmount = 92.5m
                        },
                        new
                        {
                            Id = 4,
                            OrderMasterId = 4,
                            ProductMasterId = 4,
                            Quantity = 1,
                            TotalAmount = 24.25m
                        },
                        new
                        {
                            Id = 5,
                            OrderMasterId = 5,
                            ProductMasterId = 5,
                            Quantity = 1,
                            TotalAmount = 27.89m
                        },
                        new
                        {
                            Id = 6,
                            OrderMasterId = 6,
                            ProductMasterId = 6,
                            Quantity = 1,
                            TotalAmount = 610m
                        },
                        new
                        {
                            Id = 7,
                            OrderMasterId = 7,
                            ProductMasterId = 7,
                            Quantity = 1,
                            TotalAmount = 1000.16m
                        },
                        new
                        {
                            Id = 8,
                            OrderMasterId = 8,
                            ProductMasterId = 8,
                            Quantity = 1,
                            TotalAmount = 85.74m
                        },
                        new
                        {
                            Id = 9,
                            OrderMasterId = 9,
                            ProductMasterId = 9,
                            Quantity = 1,
                            TotalAmount = 52.5m
                        },
                        new
                        {
                            Id = 10,
                            OrderMasterId = 10,
                            ProductMasterId = 10,
                            Quantity = 1,
                            TotalAmount = 66.79m
                        },
                        new
                        {
                            Id = 11,
                            OrderMasterId = 11,
                            ProductMasterId = 11,
                            Quantity = 1,
                            TotalAmount = 18.95m
                        },
                        new
                        {
                            Id = 12,
                            OrderMasterId = 12,
                            ProductMasterId = 12,
                            Quantity = 1,
                            TotalAmount = 63.67m
                        },
                        new
                        {
                            Id = 13,
                            OrderMasterId = 13,
                            ProductMasterId = 13,
                            Quantity = 2,
                            TotalAmount = 139.38m
                        },
                        new
                        {
                            Id = 14,
                            OrderMasterId = 14,
                            ProductMasterId = 14,
                            Quantity = 2,
                            TotalAmount = 138.34m
                        },
                        new
                        {
                            Id = 15,
                            OrderMasterId = 15,
                            ProductMasterId = 15,
                            Quantity = 2,
                            TotalAmount = 34.84m
                        },
                        new
                        {
                            Id = 16,
                            OrderMasterId = 10,
                            ProductMasterId = 1,
                            Quantity = 1,
                            TotalAmount = 12.15m
                        },
                        new
                        {
                            Id = 17,
                            OrderMasterId = 11,
                            ProductMasterId = 2,
                            Quantity = 1,
                            TotalAmount = 20m
                        },
                        new
                        {
                            Id = 18,
                            OrderMasterId = 12,
                            ProductMasterId = 3,
                            Quantity = 1,
                            TotalAmount = 92.5m
                        });
                });

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.OrderMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerMasterId")
                        .HasColumnType("int");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerMasterId");

                    b.ToTable("OrderMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(507),
                            CustomerMasterId = 1,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 12.15m
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(511),
                            CustomerMasterId = 2,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 20m
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(514),
                            CustomerMasterId = 3,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 92.5m
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(516),
                            CustomerMasterId = 4,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 24.25m
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(518),
                            CustomerMasterId = 5,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 27.89m
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(520),
                            CustomerMasterId = 6,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 610m
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(522),
                            CustomerMasterId = 7,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 1000.16m
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(524),
                            CustomerMasterId = 8,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 85.74m
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(526),
                            CustomerMasterId = 9,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 52.5m
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(528),
                            CustomerMasterId = 10,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 78.94m
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(530),
                            CustomerMasterId = 11,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 38.95m
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(532),
                            CustomerMasterId = 12,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 156.17m
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(534),
                            CustomerMasterId = 13,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 139.38m
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(536),
                            CustomerMasterId = 14,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 138.34m
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(538),
                            CustomerMasterId = 15,
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalOrderAmount = 34.84m
                        });
                });

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.ProductMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(197),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12.15m,
                            ProductName = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(216),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 20m,
                            ProductName = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(219),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 92.5m,
                            ProductName = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(221),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 24.25m,
                            ProductName = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(224),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 27.89m,
                            ProductName = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(226),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 610m,
                            ProductName = "Product 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(228),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1000.16m,
                            ProductName = "Product 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(230),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 85.74m,
                            ProductName = "Product 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(232),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 52.5m,
                            ProductName = "Product 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(235),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 66.79m,
                            ProductName = "Product 10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(237),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 18.95m,
                            ProductName = "Product 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(250),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 63.67m,
                            ProductName = "Product 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(252),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 69.69m,
                            ProductName = "Product 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(254),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 69.17m,
                            ProductName = "Product 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 16, 27, 4, 170, DateTimeKind.Local).AddTicks(257),
                            DeletedBy = 0,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 17.42m,
                            ProductName = "Product 15"
                        });
                });

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.OrderDetailMaster", b =>
                {
                    b.HasOne("AngularDemoSeeds.EntityFrameworkCore.Entity.OrderMaster", "OrderMaster")
                        .WithMany("OrderDetailMasters")
                        .HasForeignKey("OrderMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AngularDemoSeeds.EntityFrameworkCore.Entity.ProductMaster", "ProductMaster")
                        .WithMany("OrderDetailMasters")
                        .HasForeignKey("ProductMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderMaster");

                    b.Navigation("ProductMaster");
                });

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.OrderMaster", b =>
                {
                    b.HasOne("AngularDemoSeeds.EntityFrameworkCore.Entity.CustomerMaster", "CustomerMaster")
                        .WithMany("OrderMasters")
                        .HasForeignKey("CustomerMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerMaster");
                });

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.CustomerMaster", b =>
                {
                    b.Navigation("OrderMasters");
                });

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.OrderMaster", b =>
                {
                    b.Navigation("OrderDetailMasters");
                });

            modelBuilder.Entity("AngularDemoSeeds.EntityFrameworkCore.Entity.ProductMaster", b =>
                {
                    b.Navigation("OrderDetailMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
